name: Arduino Console CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: arduino-console

    steps:
      - uses: actions/checkout@v4

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio

      - name: Install PlatformIO
        run: pip install platformio

      - name: Compile projeto
        run: pio run -e uno

      - name: Checar uso de RAM
        run: pio run -e uno 2>&1 | grep -E "RAM|Flash"
